server:
  port: 80
#  servlet:
#    context-path: /Shopme
spring:
  datasource:
    password: Minh@vu87
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root    
    hikari:      
       minimum-idle: 1
       maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 749107562541-f3rhamojpc7lgn25h0er5ldnkmp12538.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 383630090108913
            client-secret: a1ab335184027c1a9dd6f7e660b9c04a
            scope:
            - email
            - public_profile
          